#
# config.yaml
#
# This is an example Synse Plugin configuration for the Juniper JTI Plugin.
# It is not intended to be used as a default configuration for the plugin,
# but can serve as a reference for configuring your own config.
#

version: 3
debug: true
network:
  type: tcp
  address: ':5010'
settings:
  mode: parallel
  read:
    # This interval may be tuned to be closer to the interval at which
    # configured Juniper equipment reports data over the JTI stream.
    interval: 1s
  write:
    enabled: false
  listen:
    enabled: false
  cache:
    enabled: true
    ttl: 5m
dynamicRegistration:
  config:
    - address: udp://0.0.0.0:5566